spring:
  application:
    name: shopping-service
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t