server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fernandodlmf/com.springcloudexample.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
        bootstrap: false
  security:
    user:
      password: s3cr3t
      name: root
